language: node_js
node_js: stable
sudo: required
dist: trusty
before_install:
  - cd cockpit
install:
  - npm install
script:
  - npm run test
  - npm run build
  - sonar-scanner
before_deploy:
  - cd build

addons:
  sonarcloud:
    organization: "mariusgiger-github"
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
